---
- name: Configure all servers
  hosts: all
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/common.yaml
  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: Configure load balancer
  hosts: loadbalancer
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/loadbalancer.yaml
  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

- name: Configure web servers
  hosts: webservers
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/webservers.yaml
  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

- name: Configure application server
  hosts: app
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/app.yaml
  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted

- name: Configure ci/cd server
  hosts: cicd
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/cicd.yaml
  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted

- name: Configure Jenkins deployment access
  hosts: app
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/deployment-access.yaml
